<a href="https://colab.research.google.com/github/hisjeans/data-analysis-ml/blob/main/22321643_%E1%84%8E%E1%85%AC%E1%84%8C%E1%85%B5%E1%86%AB%E1%84%92%E1%85%B4_Pandas%E1%84%80%E1%85%AA%E1%84%8C%E1%85%A6_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 과제

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## 1) 타이타닉 데이터를 데이터프레임으로 불러오기
### A. 과제게시판 - 타이타닉데이터 다운로드 및 데이터 불러오기

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/2025_2학기_데이터분석과머신러닝/타이타닉데이터셋.csv")

## 2) 타이타닉 데이터 프레임에 대해 요약 기능 사용하기

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

### 타이타닉 데이터 컬럼 설명
- PassangerID : 승객 ID
- Survived : 생존 여부, 0=사망, 1=생존
- Pclass : 티켓의 등급 (1=1st, 2=2nd, 3=3rd)
- Name : 승객의 이름
- Sex : 성별
- Age : 연력
- SibSp : 타이타닉호에 탑승한 형제/배우자의 수
- Parch : 타이타닉호에 탑승한 부모/자녀 수
- Ticket : 티켓 번호
- Fare : 승객 요금
- Cabin : 객실 번호
- Embarked : 탑승 위치

In [ ]:
del df['Cabin']
df = df.dropna()
df = df.reset_index(drop=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S

## 3) 타이타닉 데이터 프레임 Human_classfi 컬럼 추가하기
- 남자이며, 19세 미만은 [Child_m]으로 설정
- 여자이며, 19세 미만은 [Child_f]으로 설정
- 남자이며, 19세 이상은 [Mr]으로 설정
- 여자이며, 19세 미만은 [Ms]으로 설정

In [ ]:
df.loc[(df['Sex'] == 'male')&(df['Age']<19), 'Human_classfi'] = 'Child_m'
df.loc[(df['Sex'] == 'female')&(df['Age']<19), 'Human_classfi'] = 'Child_f'
df.loc[(df['Sex']=='male')&(df['Age']>=19),'Human_classfi']='Mr'
df.loc[(df['Sex']=='female')&(df['Age']>=19),'Human_classfi']='Ms'
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Human_classfi
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Ms
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Ms
...,...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S,Child_f
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q,Ms
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S,Ms
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,Ms
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr

## 4) 아래의 데이터 프레임을 타이타닉 데이터 프레임에 조인하기

In [ ]:
data_dict = {
    "Human_classfi" : ['Child_m', 'Child_f', 'Mr','Ms'],
    "HC_DES" : ['19세 미만의 남성', '19세 미만의 여성','19세 이상의 남성','19세 이상의 여성']
}
des_df = pd.DataFrame(data_dict)
des_df

  Human_classfi      HC_DES
0       Child_m  19세 미만의 남성
1       Child_f  19세 미만의 여성
2            Mr  19세 이상의 남성
3            Ms  19세 이상의 여성

In [ ]:
df=df.merge(des_df, how='left', on='Human_classfi')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Human_classfi,HC_DES
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,Q,Mr,19세 이상의 남성
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,S,Ms,19세 이상의 여성
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,Q,Mr,19세 이상의 남성
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,S,Mr,19세 이상의 남성
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,S,Ms,19세 이상의 여성
...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,S,Child_f,19세 미만의 여성
327,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,Q,Ms,19세 이상의 여성
328,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,S,Ms,19세 이상의 여성
329,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C,Ms,19세 이상의 여성
330,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,S,Mr,19세 이상의 남성

## 5) Human_classfi 별 생존자 수 확인하기

In [ ]:
df.groupby('Human_classfi')['Survived'].sum()

Human_classfi
Child_f     25
Child_m      0
Mr           0
Ms         102
Name: Survived, dtype: int64